### ISSUE TITLE
App can not be Installed

### ISSUE THREAD

**Issue by rizwankhan003** [dzmanto/foehnix#3]
#### Expected behavior
I should be able to install the app after downloading the apk file.

#### Actual behavior
 After downloading the apk and trying to install it show message "app not installed"

#### How to reproduce
* Download the apk file from releases page.
* Try to package install the app.
* Note the bug 
---
* Browser: foehnix 2.3
* Operating system: Android version 7.0
* Device: HUAWEI Mate 10 lite
#### Recording Of The Bug
https://www.youtube.com/watch?v=EESLqmVhObI

**Comment by Perflyst** [comment]
Looks like there is already an app installed with the package name `foehnix.widget`.

Please look at your apps if the F-Droid or amazon version is installed. Remove it and try again.

**Comment by dzmanto** [comment]
Dear rizwankhan003:

The issue should be resolved. Do you want to try again?

Cheers,

Dani
