### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [dzmanto/foehnix#6]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by Korb** [comment]
![Screenshot_2024_0331_141816_org fdroid fdroid](https://github.com/dzmanto/foehnix/assets/3509797/5a6dc5fd-c1c8-4e94-8dc5-a6107dc158e4)
